#!/bin/bash
set -e

S3_BUCKET=nextcaltrain.com
CLOUDFRONT_DISTRIBUTION=E3CI6YHVG0UNH0

day=$(expr 60 \* 60 \* 24)
week=$(expr $day \* 7)
year=$(expr $day \* 365)

# upload NAME TYPE MAXAGE
upload() {
	aws s3 cp - \
		s3://$S3_BUCKET/$1 \
		--region us-east-1 \
		--acl public-read \
		--content-type "$2" \
		--cache-control "max-age=$3, public" \
		--content-language en
}

./generate | upload index.html "text/html; charset=utf-8" $day
cat error.html | upload error.html "text/html; charset=utf-8" $year

echo "Deploy complete. You may safely exit."
echo
echo "Waiting for cache invalidation. This could take a while..."
node_modules/.bin/cf-invalidate --wait -- $CLOUDFRONT_DISTRIBUTION index.html error.html
