#!/usr/bin/env node
"use strict";

var http = require("http");
var getport = require("getport");
var generate = require("./styleguide.js");

function handle(req, res) {
  if (req.url === "/") {
    res.setHeader("Content-Type","text/html; charset=UTF-8");
    generate().pipe(res);
  }
  else {
    send404(req, res);
  }
}

function send404(req, res) {
  res.statusCode = 404;
  res.end("Not found.");
}

var server = http.createServer(handle);

getport(function(err, port) {
  if (err) {
    throw err;
  }
  server.listen(port);
  console.log("Listening on port", port);
});

