#!/usr/bin/env node
"use strict";

var fs = require("fs");

require("./generate").watch().on("data", function(stream) {
  process.stdout.write(".");
  stream.pipe(fs.createWriteStream("index.html"));
});
